repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/psf/black
      rev: 19.3b0
      hooks:
          - id: black
    - repo: https://github.com/pycqa/isort
      rev: 5.5.2
      hooks:
          - id: isort
            name: isort (python)
          - id: isort
            name: isort (cython)
            types: [cython]
          - id: isort
            name: isort (pyi)
            types: [pyi]
