distri: focal
language: python
python:
  - "3.8"

before_script:
  - pip install -r requirements.txt
  - install-webdrivers --path ./

branches:
  only:
    - master

env: DJANGO_SETTINGS_MODULE="portfolio_and_blog.settings.travis"

services:
  - postgresql

script:
  - coverage run --source='user' --omit='user/__init__.py','user/admin.py','user/tests*','user/apps.py','user/urls.py','user/migrations/*', manage.py test user.tests
  - coverage run --source='business' --omit='business/__init__.py','business/admin.py','business/tests*','business/launch_data_fill.py','business/apps.py','business/urls.py','business/migrations/*','business/test_functional.py'  manage.py test business.tests business.tests_unit
  - coverage report
