# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: youpiyoful
      POSTGRES_PASSWORD: 12345
      PGDATA: /var/lib/pgsql/data
    volumes:
      - postgres:/data/postgres

volumes:
    postgres:
