# Generated by Django 3.2.5 on 2021-07-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "level_experience",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("year_of_experience", models.DateField()),
            ],
        )
    ]
