# Generated by Django 3.2.5 on 2021-07-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("portfolio", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("technology", models.CharField(max_length=300)),
                ("image", models.ImageField(upload_to="projects")),
            ],
        )
    ]
